#!/bin/sh

#Destination Port
DEST_PORT=7001

# Get IP address and Hostname
IP_ADDRESS=$(ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)
HOSTNAME=$(hostname)

NETWORK_PART=$(echo $IP_ADDRESS | cut -d '.' -f 1-3)
BROADCAST="$NETWORK_PART.255"

# Combine the information
MESSAGE="IP Address: $IP_ADDRESS, Hostname: $HOSTNAME"

# Destination details
DEST_IP=$BROADCAST

while true; do
    # Send the message through UDP
    echo "$MESSAGE" | nc -ubw 1 $DEST_IP $DEST_PORT

    echo "Message sent: $MESSAGE"

    # Wait for 1 second before the next run
    sleep 1
done
